# Generated by Django 4.2.7 on 2023-12-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_App', '0003_alter_socios_socio_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='Socio_Estado',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Suspendido', 'Suspendido'), ('Retirado', 'Retirado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='socios',
            name='Socio_Sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=30),
        ),
    ]
