# Generated by Django 4.2.7 on 2023-12-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_App', '0004_alter_socios_socio_estado_alter_socios_socio_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='Socio_Estado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='socios',
            name='Socio_Sexo',
            field=models.CharField(max_length=30),
        ),
    ]
