# Generated by Django 4.2.7 on 2023-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba_App', '0002_alter_socios_socio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='Socio_Observacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
